### ISSUE TITLE
Level 3 Error in Validation - "MapUnits in DMU that are not present on map, in CMU, or elsewhere" when unit is cross section image

### ISSUE THREAD

**Issue by lawilliams-virginia** [usgs/gems-tools-pro#31]
Hi USGS folks-

I have a map unit that is in the cross section for a conversion project that is not a GeoloigicMap map unit due to it not being present at the surface. For this conversion, we opted to add an image of the cross section from the publication and to include that unit in the DMU as the original publication had done. When running validation, this setup yields a Level 3 GeMS error of "MapUnits in DMU that are not present on map, in CMU, or elsewhere".

Is there a suggested workaround for this issue? It would seem that somehow we would need to have this unit included in a feature class as a map unit in order to validate that geodatabase.

Thanks,
Lauren

**Comment by ethoms-usgs** [comment]
Hi Lauren,
I think what you did makes sense. If the gdb otherwise checks out at Level 3, I would just explain that in a readme or in an edited version of the HTML report itself (please add the source of your comment if you do this to keep the section separate from the rest of the automated text) and in the submission form.

Is there something in the description for the unit itself to the effect of 'shown only on cross section?'. I think that would be helpful if it's not there already.

--
​​Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage, AK 99508

________________________________
From: lawilliams-virginia ***@***.***>
Sent: Monday, August 22, 2022 9:56 AM
To: usgs/gems-tools-pro ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [usgs/gems-tools-pro] Level 3 Error in Validation - "MapUnits in DMU that are not present on map, in CMU, or elsewhere" when unit is cross section image (Issue #31)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi USGS folks-

I have a map unit that is in the cross section for a conversion project that is not a GeoloigicMap map unit due to it not being present at the surface. For this conversion, we opted to add an image of the cross section from the publication and to include that unit in the DMU as the original publication had done. When running validation, this setup yields a Level 3 GeMS error of "MapUnits in DMU that are not present on map, in CMU, or elsewhere".

Is there a suggested workaround for this issue? It would seem that somehow we would need to have this unit included in a feature class as a map unit in order to validate that geodatabase.

Thanks,
Lauren

**Comment by lawilliams-virginia** [comment]
Hi Evan-

There is a note in the DMU description saying that it is a cross section only Map Unit.

I'll check with our team to see how they would like to note this in the files.

Thanks,
Lauren

**Comment by ethoms-usgs** [comment]
Sounds great. Closing this issue.
